"""Public API for deterministic structured document representation."""

from pagetrace.structure.errors import (
    StructureDependencyError,
    StructureError,
    StructureIntegrityError,
    StructureLimitError,
    StructureProcessingError,
    StructureStorageError,
)
from pagetrace.structure.models import (
    DEFAULT_STRUCTURE_CONFIG,
    DEFAULT_STRUCTURE_LIMITS,
    PDF_LAYOUT_BACKEND_NAME,
    STRUCTURE_PROCESSOR_NAME,
    STRUCTURE_PROCESSOR_VERSION,
    STRUCTURE_SCHEMA_VERSION,
    BoundingBox,
    CoordinateOrigin,
    StructureConfig,
    StructuredDocumentArtifact,
    StructuredPage,
    StructuredTable,
    StructureLimits,
    StructureProcessorDescriptor,
    TableCell,
    TableStrategy,
    TextSpan,
    TextSpanSource,
    is_structure_artifact_id,
    span_id_for,
    structure_artifact_id_for,
    structure_content_fingerprint_for,
    table_id_for,
)
from pagetrace.structure.processing import structure_document
from pagetrace.structure.serialization import (
    deserialize_structured_document,
    serialize_structured_document,
)
from pagetrace.structure.storage import load_structured_document

__all__ = [
    "DEFAULT_STRUCTURE_CONFIG",
    "DEFAULT_STRUCTURE_LIMITS",
    "PDF_LAYOUT_BACKEND_NAME",
    "STRUCTURE_PROCESSOR_NAME",
    "STRUCTURE_PROCESSOR_VERSION",
    "STRUCTURE_SCHEMA_VERSION",
    "BoundingBox",
    "CoordinateOrigin",
    "StructureConfig",
    "StructureDependencyError",
    "StructureError",
    "StructureIntegrityError",
    "StructureLimitError",
    "StructureLimits",
    "StructureProcessingError",
    "StructureProcessorDescriptor",
    "StructureStorageError",
    "StructuredDocumentArtifact",
    "StructuredPage",
    "StructuredTable",
    "TableCell",
    "TableStrategy",
    "TextSpan",
    "TextSpanSource",
    "deserialize_structured_document",
    "is_structure_artifact_id",
    "load_structured_document",
    "serialize_structured_document",
    "span_id_for",
    "structure_artifact_id_for",
    "structure_content_fingerprint_for",
    "structure_document",
    "table_id_for",
]
