"""Public consolidated evaluation and quality API."""

from pagetrace.quality.errors import QualityError, QualityInputError, QualityIntegrityError
from pagetrace.quality.evaluation import evaluate_quality, text_quality_case
from pagetrace.quality.models import (
    DEFAULT_QUALITY_POLICY,
    DEFAULT_QUALITY_PROCESSOR,
    QUALITY_PROCESSOR_NAME,
    QUALITY_PROCESSOR_VERSION,
    QUALITY_SCHEMA_VERSION,
    AnswerQualityCase,
    EvaluationStatus,
    FindingSeverity,
    GateResult,
    HumanReview,
    MetricComparator,
    MetricGate,
    MetricObservation,
    QualityDimension,
    QualityFinding,
    QualityMetricName,
    QualityPolicy,
    QualityProcessorDescriptor,
    QualityReport,
    QualityReportStatus,
    QualitySuite,
    RegressionResult,
    RegressionRule,
    TextQualityCase,
    create_quality_suite,
    is_quality_report_id,
    is_quality_suite_id,
    metric_degradation,
)
from pagetrace.quality.serialization import (
    deserialize_quality_report,
    deserialize_quality_suite,
    serialize_quality_report,
    serialize_quality_suite,
)

__all__ = [
    "DEFAULT_QUALITY_POLICY",
    "DEFAULT_QUALITY_PROCESSOR",
    "QUALITY_PROCESSOR_NAME",
    "QUALITY_PROCESSOR_VERSION",
    "QUALITY_SCHEMA_VERSION",
    "AnswerQualityCase",
    "EvaluationStatus",
    "FindingSeverity",
    "GateResult",
    "HumanReview",
    "MetricComparator",
    "MetricGate",
    "MetricObservation",
    "QualityDimension",
    "QualityError",
    "QualityFinding",
    "QualityInputError",
    "QualityIntegrityError",
    "QualityMetricName",
    "QualityPolicy",
    "QualityProcessorDescriptor",
    "QualityReport",
    "QualityReportStatus",
    "QualitySuite",
    "RegressionResult",
    "RegressionRule",
    "TextQualityCase",
    "create_quality_suite",
    "deserialize_quality_report",
    "deserialize_quality_suite",
    "evaluate_quality",
    "is_quality_report_id",
    "is_quality_suite_id",
    "metric_degradation",
    "serialize_quality_report",
    "serialize_quality_suite",
    "text_quality_case",
]
