"""Public deterministic lexical retrieval and evaluation API."""

from pagetrace.retrieval.errors import (
    RetrievalError,
    RetrievalEvaluationError,
    RetrievalIntegrityError,
    RetrievalLimitError,
    RetrievalQueryError,
)
from pagetrace.retrieval.evaluation import evaluate_retrieval
from pagetrace.retrieval.lexical import rank_corpus, tokenize
from pagetrace.retrieval.models import (
    DEFAULT_RETRIEVAL_CONFIG,
    DEFAULT_RETRIEVAL_LIMITS,
    DEFAULT_RETRIEVAL_PROCESSOR,
    RETRIEVAL_PROCESSOR_NAME,
    RETRIEVAL_PROCESSOR_VERSION,
    RETRIEVAL_SCHEMA_VERSION,
    TOKENIZER_NAME,
    TOKENIZER_VERSION,
    RetrievalCaseMetrics,
    RetrievalConfig,
    RetrievalDataset,
    RetrievalEvaluation,
    RetrievalHit,
    RetrievalJudgment,
    RetrievalLimits,
    RetrievalProcessorDescriptor,
    RetrievalResult,
    create_retrieval_dataset,
    is_retrieval_dataset_id,
    is_retrieval_evaluation_id,
    is_retrieval_result_id,
    retrieval_dataset_id_for,
    retrieval_evaluation_id_for,
    retrieval_result_id_for,
)
from pagetrace.retrieval.processing import retrieve
from pagetrace.retrieval.serialization import (
    deserialize_retrieval_dataset,
    deserialize_retrieval_evaluation,
    deserialize_retrieval_result,
    serialize_retrieval_dataset,
    serialize_retrieval_evaluation,
    serialize_retrieval_result,
)

__all__ = [
    "DEFAULT_RETRIEVAL_CONFIG",
    "DEFAULT_RETRIEVAL_LIMITS",
    "DEFAULT_RETRIEVAL_PROCESSOR",
    "RETRIEVAL_PROCESSOR_NAME",
    "RETRIEVAL_PROCESSOR_VERSION",
    "RETRIEVAL_SCHEMA_VERSION",
    "TOKENIZER_NAME",
    "TOKENIZER_VERSION",
    "RetrievalCaseMetrics",
    "RetrievalConfig",
    "RetrievalDataset",
    "RetrievalError",
    "RetrievalEvaluation",
    "RetrievalEvaluationError",
    "RetrievalHit",
    "RetrievalIntegrityError",
    "RetrievalJudgment",
    "RetrievalLimitError",
    "RetrievalLimits",
    "RetrievalProcessorDescriptor",
    "RetrievalQueryError",
    "RetrievalResult",
    "create_retrieval_dataset",
    "deserialize_retrieval_dataset",
    "deserialize_retrieval_evaluation",
    "deserialize_retrieval_result",
    "evaluate_retrieval",
    "is_retrieval_dataset_id",
    "is_retrieval_evaluation_id",
    "is_retrieval_result_id",
    "rank_corpus",
    "retrieval_dataset_id_for",
    "retrieval_evaluation_id_for",
    "retrieval_result_id_for",
    "retrieve",
    "serialize_retrieval_dataset",
    "serialize_retrieval_evaluation",
    "serialize_retrieval_result",
    "tokenize",
]
